name: seqzip
version: 0.1.0.0
synopsis: Sequent Calculus with Zippers
description: See readme.
maintainer: Xiaoshuang Yang <thuyxs17@gmail.com>
category: Logic

ghc-options: -Wall

extra-source-files:
  - README.md
  - LICENSE
  - stack.yaml
  - package.yaml
  - lib/FormM/Parse.y
  - lib/FormM/Lex.x
  - exec/index.html

dependencies:
  - array
  - base
  - random
  - QuickCheck
  - graphviz
  - temporary
  - bytestring
  - tagged
  - hspec
  - multiset
  - process
  - containers

build-tools:
  - alex
  - happy

library:
  source-dirs: lib

executables:
  genz:
    source-dirs: exec
    main: genz.hs
    ghc-options: -Wall -threaded
    dependencies:
      - base >= 4.8 && < 5
      - seqzip
  lwb-k:
    source-dirs: exec
    main: lwb-k.hs
    ghc-options: -Wall -threaded
    dependencies:
      - base >= 4.8 && < 5
      - seqzip
  lwb-s4:
    source-dirs: exec
    main: lwb-s4.hs
    ghc-options: -Wall -threaded
    dependencies:
      - base >= 4.8 && < 5
      - seqzip
  genz-web:
    source-dirs: exec
    main: genz-web.hs
    ghc-options: -Wall -threaded
    dependencies:
      - base >= 4.8 && < 5
      - file-embed
      - js-jquery >= 3
      - scotty
      - seqzip
      - template-haskell
      - text
      - warp

tests:
  Test:
    main: Test.hs
    source-dirs: test
    dependencies:
      - seqzip
      - QuickCheck
      - hspec

benchmarks:
  runtime:
    source-dirs: bench
    main: runtime.hs
    dependencies:
      - base >= 4.8 && < 5
      - bytestring
      - cassava
      - criterion
      - directory
      - scientific
      - seqzip
      - split
      - vector
  memory:
    source-dirs: bench
    ghc-options: -rtsopts
    main: memory.hs
    dependencies:
      - base >= 4.8 && < 5
      - seqzip
      - weigh
